<?php
  // This file is generated by Composer
  require_once 'vendor/autoload.php';

  // Load .env file
  Dotenv::load(__DIR__);

  $githubUsername = 'frdmn';

  $client = new \Github\Client();

  $client->authenticate(getenv('GITHUB_API_TOKEN'), null, Github\Client::AUTH_HTTP_TOKEN);

  $repositories = $client->api('user')->repositories($githubUsername);

  var_dump($repositories);
?>
