<?php
  // This file is generated by Composer
  require_once 'vendor/autoload.php';

  // Load .env file
  Dotenv::load('.env');

  $githubUsername = 'frdmn';

  $client = new \Github\Client();

  $repositories = $client->api('user')->repositories($githubUsername);

  var_dump($repositories);
?>
