<?php
  // This file is generated by Composer
  require_once 'vendor/autoload.php';

  // Load .env file
  Dotenv::load(__DIR__);

  // Function to calculate the percentage
  function percent($amount, $total) {
    $countA = $amount / $total;
    $countB = $countA * 100;
    // Round number
    $count = number_format($countB, 0);
    return $count;
  }

  // Store GitHub username to work with
  $githubUsername = 'frdmn';

  // Initiate API client
  $client = new \Github\Client();

  // Authenticate using API token in .env
  $client->authenticate(getenv('GITHUB_API_TOKEN'), null, Github\Client::AUTH_HTTP_TOKEN);

  // Fetch all repositories
  $paginator  = new Github\ResultPager($client);
  $repositories     = $paginator->fetchAll($client->api('user'), 'repositories', array($githubUsername));

  // Loop through repos
  foreach ($repositories as $repository) {
    // Store informations in temporary object
    $json_prepare['projects'][$repository['name']]['name'] = $repository['name'];
    $json_prepare['projects'][$repository['name']]['description'] = $repository['description'];
    $json_prepare['projects'][$repository['name']]['github'] = $repository['full_name'];
    $json_prepare['projects'][$repository['name']]['stars'] = $repository['stargazers_count'];
    $json_prepare['projects'][$repository['name']]['watcher'] = $repository['watchers_count'];
    $json_prepare['projects'][$repository['name']]['forks'] = $repository['forks'];
    $json_prepare['projects'][$repository['name']]['language'] = $repository['language'];
    $json_prepare['projects'][$repository['name']]['created'] = $repository['created_at'];
    $json_prepare['projects'][$repository['name']]['updated'] = $repository['updated_at'];

    // Languages
    $languages = $client->api('repo')->languages($githubUsername, $repository['name']);
    foreach ($languages as $language => $size) {
      $json_prepare['projects'][$repository['name']]['languages'][$language] = percent($size, array_sum($languages));
    }
  }

  // Encode as JSON and print
  $json = json_encode($json_prepare);
  echo $json;

  // Dump if /?dump is set
  if (isset($_GET['dump'])) {
    var_dump($repositories);
  }
?>
