<?php
  // This file is generated by Composer
  require_once 'vendor/autoload.php';

  // Load .env file
  Dotenv::load(__DIR__);

  // Function to calculate the percentage
  function percent($amount, $total) {
    $countA = $amount / $total;
    $countB = $countA * 100;
    // Round number
    $count = number_format($countB, 0);
    return $count;
  }

  // Load portfolio data
  $info_json = json_decode(file_get_contents("data/info.json"), true);

  if (!getenv('GITHUB_API_TOKEN')) {
    die('No "GITHUB_API_TOKEN" found in .env file!');
  }

  // Initiate API client
  $client = new \Github\Client();

  // Authenticate using API token in .env
  $client->authenticate(getenv('GITHUB_API_TOKEN'), null, Github\Client::AUTH_HTTP_TOKEN);

  foreach ($info_json['projects'] as $name => $project) {
    $repository = $client->api('repo')->show($project['owner'], $project['alias']);

    $json_prepare['projects'][$project['owner'].'/'.$project['alias']]['name'] = $repository['name'];
    $json_prepare['projects'][$project['owner'].'/'.$project['alias']]['description'] = $repository['description'];
    $json_prepare['projects'][$project['owner'].'/'.$project['alias']]['github'] = $repository['full_name'];
    $json_prepare['projects'][$project['owner'].'/'.$project['alias']]['stars'] = $repository['stargazers_count'];
    $json_prepare['projects'][$project['owner'].'/'.$project['alias']]['watcher'] = $repository['watchers_count'];
    $json_prepare['projects'][$project['owner'].'/'.$project['alias']]['forks'] = $repository['forks'];
    $json_prepare['projects'][$project['owner'].'/'.$project['alias']]['language'] = $repository['language'];
    $json_prepare['projects'][$project['owner'].'/'.$project['alias']]['created'] = $repository['created_at'];
    $json_prepare['projects'][$project['owner'].'/'.$project['alias']]['updated'] = $repository['updated_at'];

    // Languages
    $languages = $client->api('repo')->languages($project['owner'], $project['alias']);
    foreach ($languages as $language => $size) {
      $json_prepare['projects'][$project['owner'].'/'.$project['alias']]['languages'][$language] = percent($size, array_sum($languages));
    }
  }

  // Encode as JSON and print
  $json = json_encode($json_prepare, JSON_PRETTY_PRINT);
  echo $json;

  // Dump if /?dump is set
  if (isset($_GET['dump'])) {
    var_dump($repositories);
  }
?>
